### PR TITLE
Mm 0.9.x

### PR DESCRIPTION
**Pull request by jamieorc**
I forked and updated code with fixes and tests for EmbeddedDocument use.

new class method "nullify_nil_attachments_attributes()" called before_save
class method "destroy_nil_attachments()" now only calls gid.delete(id) after_save
changed @nil_attachments from Set to Hash key is still name, value is the file id
these changes obviate the need for calling set() after_save, so works with EmbeddedDocument

PS: not sure how to send pull request for the MM-0.8.x branch. Perhaps you can branch from v0.5.5 and I can send a pull request to that.

### CODE REVIEW

**Comment by bkeepers** [comment]
Pulled, thanks!

Next time, would you mind doing the changes to gemspec in a different branch? I had to pull those commits out, which will likely mess some things up for you.

**Comment by jamieorc** [comment]
Excellent. No problem about the gemspec. Wasn't sure correct procedure, but I can do those elsewhere than for the pull request. Interested in getting the MM 0.8.6 changes? If so, make a branch (maybe it should be something like Joint-0.5.x) and I'll send a pull request for those.

**Comment by bkeepers** [comment]
Doesn't matter to me. I'm not sure how many people are still using 0.8.6.

**Comment by jamieorc** [comment]
Just noticed you haven't released a new version of the gem with the fix. Coming soon?

**Comment by bkeepers** [comment]
Done. Thanks @jamieorc for the prodding.

**Comment by jamieorc** [comment]
You're welcome. :-)

**Pull request closed without merging**
